# Generated by Django 3.1 on 2020-09-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='iso',
            name='name',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name',
        ),
        migrations.RemoveField(
            model_name='states',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='iso',
            name='iso',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='region',
            name='region',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='states',
            name='states',
            field=models.CharField(default='', max_length=200),
        ),
    ]
