# Generated by Django 3.1 on 2020-09-09 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20200909_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='picture',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
