# Generated by Django 3.1 on 2020-09-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20200909_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='picture',
        ),
    ]
